name: 🤖 Agentic AI Analysis 🧠

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install anthropic pandas openpyxl

      - name: Run Claude agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python claude_agent.py

      - name: Commit Excel file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add basic_scoping/amsbasic-*.xlsx
          git commit -m "Update URL grouping analysis [skip ci]"
          git push